# Custom Language File for Launcher Customizer

[ejs.app]
title = "Block Wars Launcher"

[ejs.landing]
mediaWebsiteURL = "https://blockwars.games"
mediaXURL = "https://x.com/BlockWarsEvent"
mediaYouTubeURL = "https://www.youtube.com/@BlockWarsEvent"

[ejs.settings]
sourceGithubLink = "https://github.com/BlockWarsMC/BlockWarsLauncher"
supportLink = "https://github.com/BlockWarsMC/BlockWarsLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO BLOCK WARS"
welcomeDescription = "This launcher is the easiest way to get the optimal expierence playing Block Wars. Just log in and press play."
welcomeDescCTA = "Hope you all enjoy the event!"
